### ISSUE TITLE
Data duration as string  

### ISSUE THREAD

**Issue by ibandim123** [DouglasVarollo/NLW5-react#1]
<h1>In [slug].tsx , line 18</h1>

type Episode = {
  id: string;
  title: string;
  thumbnail: string;
  members: string;
  *duration: string;*
  durationAsString: string;
  url: string;
  publishedAt: string;
  description: string;
};

This data "duration" is a string or number??

**Comment by DouglasVarollo** [comment]
Is a number. I need to fix.
https://github.com/DouglasVarollo/NLW5-react/blob/main/server.json#L13

**Comment by DouglasVarollo** [comment]
https://github.com/DouglasVarollo/NLW5-react/commit/a526962723e07f85bf51e38d46fca4a1ee3e7c12
